INSERT INTO ALTERNATIVE (IDALT, ANAME) VALUES (1, 'HP 2017 15.6" Full-HD IPS UWVA Laptop');
INSERT INTO ALTERNATIVE (IDALT, ANAME) VALUES (2, 'Dell Latitude E7470 Business Ultrabook');
INSERT INTO ALTERNATIVE (IDALT, ANAME) VALUES (3, 'Apple MacBook Pro MF839LL/A');
INSERT INTO ALTERNATIVE (IDALT, ANAME) VALUES (4, 'Lenovo Yoga');
INSERT INTO ALTERNATIVE (IDALT, ANAME) VALUES (5, 'ASUS K501UW-AB78');